language: android

sudo: false

jdk:
  - oraclejdk8

android:
  components:
  - build-tools-25.0.0
  - android-25
  - extra-android-support
  - extra-android-m2repository

script:
  - jdk_switcher use oraclejdk8
  - ./gradlew build